### ISSUE TITLE
Is there a way to compute distances without intermediate files?

### ISSUE THREAD

**Issue by sgbaird** [CumbyLab/gridrdf#2]
It looks like this depends on reading and writing matrices to and from CSV files. Are there built-in utilities for passing this information directly rather than relying on intermediate files?

**Comment by jcumby** [comment]
The main entry point is currently `data_prepare.batch_rdf` which inherently writes to disk, but there is nothing to prevent you from passing GRID arrays around directly; the key steps involved are:
1. `extendRDF.get_rdf_and_atoms`
2. `extendRDF.rdf_kde` (or `rdf_histo` to avoid the Gaussian broadening)

I'll try to add an example showing how to manipulate structures directly (also addressing #3 ) in the short term. In the longer term, the code needs to be rearranged to make more efficient use of these functions (e.g. adding multiprocessing support).
