### ISSUE TITLE
Example of computing pairwise distances between pymatgen Structure objects

### ISSUE THREAD

**Issue by sgbaird** [CumbyLab/gridrdf#3]
Would you mind providing an example of this? I think it would be a useful addition to the docs and/or added as an extra utility given the ubiquitousness of the `pymatgen` `Structure` representation.

```python
from pymatgen.core.lattice import Lattice
from pymatgen.core.structure import Structure
dummy_structures = [
    Structure(Lattice.from_parameters(a=3.84, b=3.84, c=3.84, alpha=120, beta=90, gamma=60), ["Si", "Si"], [[0, 0, 0], [0.75, 0.5, 0.75]]),
    Structure(Lattice.from_parameters(a=3.84, b=3.84, c=3.84, alpha=120, beta=90, gamma=60), ["Ni", "Ni"], [[0, 0, 0], [0.75, 0.5, 0.75]]),
]
```

**Comment by jcumby** [comment]
I've added the script `examples/direct_grid_calculation_without_files.py` which gives an idea of how to run gridrdf as part of a more flexible workflow. The data structure of the code needs to be updated to better handle these use cases, but hopefully it will give you a starting point.

**Comment by sgbaird** [comment]
Thank you!
